name: Deploy Wordle
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
      - name: Install node_modules
        run: npm install
      - name: Build And Deploy
        run: npm run deploy