name: Deploy Wordle
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Github
        run: |
          git config --global user.email "shettypriyesh761@gmail.com"
          git config --global user.name "Priyesh Shetty"
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
      - name: Install node_modules
        run: npm install
      - name: Build And Deploy
        run: npm run deploy